version: '2'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    # environment:
    #   - VIRTUAL_HOST=your_domain
    #   - LETSENCRYPT_HOST=your_domain